### ISSUE TITLE
部分语法报错

### ISSUE THREAD

**Issue by Tindtily** [lincenying/stylelint-config#1]
下面的scss在lint时会报错
<img width="1062" alt="image" src="https://github.com/user-attachments/assets/525e29a8-1c23-4c05-939b-f260f8b06700">

```
// 定义常用的边距变量
$margin-bottom: (
    4: 4rpx,
    8: 8rpx,
    24: 24rpx,
    32: 32rpx,
    37: 37rpx,
    40: 40rpx,
    60: 60rpx
);
$margin-top: (
    24: 24rpx,
    32: 32rpx,
    37: 37rpx,
    40: 40rpx,
    60: 60rpx,
    88: 88rpx
);
$margin-left: (
    8: 8rpx
);
$margin-right: (
    20: 20rpx
);

// 使用边距变量定义样式类
@mixin margin-bottom($key) {
    margin-bottom: map-get($margin-bottom, $key);
}

@mixin margin-top($key) {
    margin-top: map-get($margin-top, $key);
}

@mixin margin-left($key) {
    margin-left: map-get($margin-left, $key);
}

@mixin margin-right($key) {
    margin-right: map-get($margin-right, $key);
}

.mgb4 { @include margin-bottom(4); }
.mgb8 { @include margin-bottom(8); }
.mgb24 { @include margin-bottom(24); }
.mgb40 { @include margin-bottom(40); }
.mgb60 { @include margin-bottom(60); }

.mgt32 { @include margin-top(32); }
.mgt24 { @include margin-top(24); }
.mgt37 { @include margin-top(37); }
.mgt40 { @include margin-top(40); }
.mgt88 { @include margin-top(88); }

.mgl8 { @include margin-left(8); }
.mgr20 { @include margin-right(20); }
```

.stylelintrc.json配置

```
{
  "extends": ["@lincy/stylelint-config"],
  "rules": {
    "at-rule-no-unknown": [
      true,
      {
        "ignoreAtRules": ["tailwind", "apply", "variants", "responsive", "screen", "use"]
      }
    ]
  }
}
```

我对scss不太熟悉，不知道应该怎么配置

**Comment by lincenying** [comment]
升级下版本, 然后把
```
"at-rule-no-unknown": [
      true,
      {
        "ignoreAtRules": ["tailwind", "apply", "variants", "responsive", "screen", "use"]
      }
    ]
```
删除

另外有一些scss的全局函数名, 官方有做修改, 如 map-get 改成了 map.get
具体请参考
https://github.com/sass/sass/blob/main/accepted/module-system.md#built-in-modules-1

**Comment by lincenying** [comment]
```scss
@use 'sass:map';
$margin-bottom: (
    4: 4rpx,
    8: 8rpx,
    24: 24rpx,
    32: 32rpx,
    37: 37rpx,
    40: 40rpx,
    60: 60rpx
);

@mixin margin-bottom($key) {
    margin-bottom: map.get($margin-bottom, $key);
}

.mb4 {
    @include margin-bottom(4);
}

```
